### ISSUE TITLE
make_tmpname sprintf throwing TypeError: can't convert nil into Integer

### ISSUE THREAD

**Issue by ghost** [akdubya/rack-thumb#2]
TypeError: can't convert nil into Integer
    /image-server/lib/thumb.rb:10:in `sprintf'

I am running Ruby 1.9.2 rc1.

Upon inspection of the method, basename is foobar_50x50.jpg, but n is nil. The issue seems to be in the initializer.

Performing the same example in Ruby 1.8.7p174 and 1.9.1p378, n has a value of zero.

Let me know if I can be of further assistance.

-stan

**Comment by akdubya** [comment]
I think I know what the issue is. I'll take a look this weekend.

**Comment by ghost** [comment]
Any news regarding a fix for this?

**Comment by akdubya** [comment]
Just pulled a commit for this.

**Comment by oliverbarnes** [comment]
hey akdubya, I was still getting that error even with the latest commit (with ruby 1.9.2-p0). 

got it working with oliverbarnes@bd219a508e032c4300d548c65700a38bdefa978c , based on a similar patch to paperclip:

https://github.com/dwalters/paperclip/commit/2a85add5f102db8773518f8ac30f7e2337bf7d13
