### ISSUE TITLE
How to use it with images from databases

### ISSUE THREAD

**Issue by oliverbarnes** [akdubya/rack-thumb#4]
Hello again Aleksander,

May I ask how you use Rack::Thumb with images stored in CouchDB? 

Been trying to use it in front of a middleware fetching images from Mongo, but no luck so far.

The original response I was sending was

  [200, { 'Content-Type' => 'image/png' }, @avatar.image.read ] 

but then it seems a #path method is expected. I tried to implement it on the middleware itself (returning the read output), and then passing self as the response body, but then a regular response #each method is expected... and i haven't yet figured how to implement it so it iterates through the image data.

any pointers would be greatly appreciated :) 

thanks for the great gem, btw

**Comment by akdubya** [comment]
Per the rack spec, response bodies must respond to #each. The code you posted above will work if you enclose the body element in brackets:

```
[200, { 'Content-Type' => 'image/png' }, [@avatar.image.read]]
```

**Comment by oliverbarnes** [comment]
thanks, makes sense. resorted to using carrierwave + s3 for now, but might switch back, and then this would solve it
